# Generated by Django 4.2.11 on 2024-05-31 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
