# Generated by Django 4.2.11 on 2024-05-31 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfoModel',
            fields=[
                ('user_no', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_birthyear', models.CharField(max_length=50)),
                ('user_birthmonth', models.CharField(max_length=50)),
                ('user_birthday', models.CharField(max_length=50)),
                ('user_azurerole', models.BooleanField()),
                ('user_blackrole', models.BooleanField()),
                ('user_professionarea', models.CharField(max_length=50)),
                ('user_workforunit', models.CharField(max_length=50)),
                ('user_title', models.CharField(max_length=50)),
                ('user_sociallinkedin', models.CharField(max_length=200)),
                ('user_socialtwitter', models.CharField(max_length=200)),
                ('user_socialfacebook', models.CharField(max_length=200)),
                ('user_note', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_infos_model', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
