# Generated by Django 4.2.11 on 2024-05-31 11:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_userinfomodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfoModel',
            new_name='UserInfo',
        ),
    ]
