# Generated by Django 4.2.11 on 2024-05-31 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_userinfomodel_userinfo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfo',
            table='user',
        ),
    ]
