# Generated by Django 4.2.11 on 2024-05-31 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_alter_userinfo_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_info_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_infos', to=settings.AUTH_USER_MODEL),
        ),
    ]
